spring:
  application:
    name: chatbot
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5432/chatbot
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        legacy_limit_handler: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    # show-sql: true